extent.reporter.spark.start=true
extent.reporter.spark.out=test-output/SparkReport/Spark.html
extent.reporter.spark.config=src/test/resources/spark-config.xml



screenshot.dir=test-output/SparkReport/Screenshots/
screenshot.rel.path=Screenshots/
screenshot.on.run.failure=true
screenshot.compress=true

# Optional: embed images directly in HTML
# extent.reporter.spark.base64images=true
